# ========================
# Stage 1 - Build
# ========================
FROM node:22-alpine AS builder
WORKDIR /usr/bmms
COPY package*.json ./
RUN npm install
COPY ./apps ./apps/
COPY *.json ./
COPY ./libs ./libs/
# COPY .env ./
RUN npm run build

# ========================
# Stage 2 - Production
# ========================
FROM node:22-alpine
WORKDIR /usr/bmms
COPY --from=builder /usr/bmms/dist/apps/platform/llm-orchestrator ./dist/apps/platform/llm-orchestrator
COPY --from=builder /usr/bmms/apps/platform/llm-orchestrator/src/proto ./dist/apps/platform/llm-orchestrator/src/proto
COPY --from=builder /usr/bmms/dist/libs ./dist/libs/

# nhận build-arg từ bên ngoài
ARG GEMINI_API_KEY
ENV GEMINI_API_KEY=$GEMINI_API_KEY

ARG JWT_SECRET
ENV JWT_SECRET=$JWT_SECRET

ARG TOKEN_EXPIRE_TIME 
ENV TOKEN_EXPIRE_TIME=$TOKEN_EXPIRE_TIME

COPY package*.json ./
ENV NODE_ENV=production
RUN npm install --omit=dev

CMD ["node", "dist/apps/platform/llm-orchestrator/src/main.js"]
