apiVersion: v1
kind: Service
metadata:
  name: billing-svc
  namespace: finance
  labels:
    app: billing-svc
spec:
  type: NodePort
  selector:
    app: billing-svc
  ports:
    - name: http
      port: 3003
      targetPort: 3003
      protocol: TCP
