apiVersion: v1
kind: Service
metadata:
  name: payment-svc
  namespace: finance
  labels:
    app: payment-svc
spec:
  type: NodePort
  selector:
    app: payment-svc
  ports:
    - name: http
      port: 3015
      targetPort: 3015
      protocol: TCP
