apiVersion: v1
kind: Service
metadata:
  name: catalogue-svc
  namespace: product
  labels:
    app: catalogue-svc
spec:
  type: NodePort
  selector:
    app: catalogue-svc
  ports:
    - name: http
      port: 3007
      targetPort: 3007
      protocol: TCP
