apiVersion: v1
kind: Service
metadata:
  name: promotion-svc
  namespace: product
  labels:
    app: promotion-svc
spec:
  type: NodePort
  selector:
    app: promotion-svc
  ports:
    - name: http
      port: 3009
      targetPort: 3009
      protocol: TCP
