apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: customer
  labels:
    app: auth-svc
spec:
  type: NodePort
  selector:
    app: auth-svc
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
