apiVersion: v1
kind: Service
metadata:
  name: crm-orchestrator
  namespace: customer
  labels:
    app: crm-orchestrator
spec:
  type: NodePort
  selector:
    app: crm-orchestrator
  ports:
    - name: http
      port: 3002
      targetPort: 3002
      protocol: TCP
