apiVersion: v1
kind: Service
metadata:
  name: customer-svc
  namespace: customer
  labels:
    app: customer-svc
spec:
  type: NodePort
  selector:
    app: customer-svc
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
