apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
  namespace: order
  labels:
    app: inventory-svc
spec:
  type: NodePort
  selector:
    app: inventory-svc
  ports:
    - name: http
      port: 3013
      targetPort: 3013
      protocol: TCP
