apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: order
  labels:
    app: order-svc
spec:
  type: NodePort
  selector:
    app: order-svc
  ports:
    - name: http
      port: 3011
      targetPort: 3011
      protocol: TCP
