apiVersion: v1
kind: Service
metadata:
  name: subscription-svc
  namespace: order
  labels:
    app: subscription-svc
spec:
  type: NodePort
  selector:
    app: subscription-svc
  ports:
    - name: http
      port: 3012
      targetPort: 3012
      protocol: TCP
